name: Detekt Code Quality

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  merge_group:

jobs:
  detekt:
    name: Run Detekt Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: 🔧 Install dependencies
        uses: ./.github/actions/install/

      - name: Run Detekt
        env:
          FIRESTORE_DATABASE_ID: ${{ secrets.FIRESTORE_DATABASE_ID }}
          GOOGLE_OAUTH_ID: ${{ secrets.GOOGLE_OAUTH_ID }}
          GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
          W3S_AUTH_KEY: ${{ secrets.W3S_AUTH_KEY }}
        run: ./gradlew detekt --no-daemon --stacktrace
